# Item shelf lives can be either:
# In hours: (for days, use number of days * 24 format)
# or 'end_of_day': (for end of current day)
# or 2 numbers: ('thaw_hours', 'expire_hours'(total from pull)) for frozen
# or 2 numbers with 'end_of_day'("end_of_day", 6): this example end of seventh day
ITEMS = {
    "Critical Items": {
        "Tomatoes - ON LINE": 4,
        "Sandwich Lettuce - ON LINE": 4, 
        "Onions - ON LINE": 4,
        # This single item will have a tempered line. DO NOT change the wording
        "American Cheese - ON LINE": (1, 7), 
    },
    "Prepped Items": {
        "Tomatoes - Prep": "end_of_day",
        "Sandwich Lettuce - Prep": 1.5 * 24,
        "Pickles - Prep": ("end_of_day", 6),
        "Onions - Prep": 1.5 * 24,
        "Mayo - Prep": ("end_of_day", 2),
        "Apples - Prep": 1 * 24,
        "Lemonade - Prep": 2 * 24,
        "Chili Meat - To Freezer": ("end_of_day", 7),
        "Salad Blend - Walkin": "end_of_day",
        "American Cheese - Prep": 7 * 24,
        "Diced Chicken - Panned": 2 * 24,
        "Cheese Sauce - Panned": 2 * 24,
        "Burrito - Made": 1.5,
        "Cold Brew - Prep": "end_of_day",
    },
    "Frozen Items": {
        "Tortillas": (24, 3 * 24),
        "Cinnabons": (24, 3 * 24),
        "Cinnabon Frosting": (24, 90 * 24),
        "Biscuits": (24, 3 * 24),
        "Croissants": (24, 3 * 24),
        "Cheese Sauce": (24, 3 * 24),
        "Chili Base": (12, 1.5 * 24),
        "Chili Beans": (12, 1.5 * 24),
        "Chili Meat - To Thaw": (12, 2 * 24),
        "Buns - Premium/Value": (24, 3 * 24),
        "Lemonade": (12, 13 * 24),
        "Pineapple Mango": (24, 35 * 24),
        "Tangerine Twist": (24, 36 * 24),
        "Fire Roasted Corn": (24, 4 * 24),
        "Diced Chicken": (24, 4 * 24),
        "Diced Eggs": (24, 5 * 24),
        "Breakfast Cheese Sauce": (24, 4 * 24),
        "Honey Butter": (24, 14 * 24),
       },
    "Opened Items(In a container or wrapped, not on line)": {
        "Ranch Sauce - Open": ("end_of_day", 6),
        "Asiago - Open": ("end_of_day", 6),
        "Mustard - Open": ("end_of_day", 6),
        "Shredded Cheddar - Open": ("end_of_day", 4),
        "3-Cheese Blend - Open": ("end_of_day", 6),
        "Blue Cheese Crumbs - Open": ("end_of_day", 6),
        "Mustard - Open": 7 * 24,
        "Bacon - Open": 7 * 24,
        "Cranberries - Open": ("end_of_day", 20),
        "Chopped Romaine - Open": 1 * 24,
        "Spring Mix - Open": 2 * 24,
        "Biscuit Butter - Open": 60 * 24,
        "Chives - Open": ("end_of_day", 179),
    },
    "On-Line Items(Portioned and anywhere in production)":{
        "Diced Onion - On Line": "end_of_day",
        "Pineapple Mango - On Line": 7 * 24,
        "Cold Brew - On Line": 1 * 24,
        "Oreo Pieces - On Line": 7 * 24,
        "Monin Flavors - On Line": 60 * 24,
        "Brillance Energy - On Line": 60 * 24,
        "Toffee Pieces - On Line": 7 * 24,
        "Tangerine Twist - On Line": 7 * 24,
        "Strawberry Puree - On Line": ("end_of_day", 6),
        "Creamer Pint - On Line": ("end_of_day", 2),
        "Brownie Batter - On Line": 7 * 24,
        "Caramel Sauce - On Line": 7 * 24,
        "Honey Butter - On Line": ("end_of_day", 6),
        "Ranch Sauce - On Line": ("end_of_day", 2),
        "Chili Meat - On Line": 6,
        "Cinnabon Frosting - On Line": 2 * 24,
        "Biscuit Butter - On Line": 1 * 24,
        "Biscuit Butter - On Line": 1 * 24,
        "Buns - Premium/Value - On Line": 2,
        "Shredded Cheddar - On Line": ("end_of_day", 4),
    },

    "Cooked Items": {
        "Bacon - All Day": "end_of_day",
        "Cookies - All": "end_of_day",
        "Bacon - Fry/Potato Topping": 14,
        "Biscuit - Cooked": 1,
        "Sausage - Cooked": 2,
        "Eggs - Cooked": 1,
        "Chicken, ALL - Cooked": .5,
        "Cheese Sauce - Cooked": 6,
        "Breakfast Sauce - Cooked": 5,
        "Sausage Gravy - Prepared": 5,
        "Baked Potatoes - Cooked": 2,
        "Tortillas - Heated": 3,
    }
}